/* DO NOT EDIT THIS FILE - it is machine generated */
#include "AppDelegate.h"
#include "cocos2d.h"
#include "CCEventType.h"
#include "platform/android/jni/JniHelper.h"
#include <jni.h>
#include <android/log.h>

/* Header for class ShareSDKUtils */
#ifndef _Included_ShareSDKUtils
#define _Included_ShareSDKUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ShareSDKUtils
 * Method:    onCancel
 * Signature: (Lcn/sharesdk/framework/Platform;I)V
 */
JNIEXPORT void JNICALL Java_cn_sharesdk_ShareSDKUtils_onCancel
		(JNIEnv * env, jobject thiz, jobject platform, jint action);

/*
 * Class:     ShareSDKUtils
 * Method:    onComplete
 * Signature: (Lcn/sharesdk/framework/Platform;ILjava/util/HashMap;)V
 */
JNIEXPORT void JNICALL Java_cn_sharesdk_ShareSDKUtils_onComplete
		(JNIEnv * env, jobject thiz, jobject platform, jint action, jobject res);

/*
 * Class:     ShareSDKUtils
 * Method:    onError
 * Signature: (Lcn/sharesdk/framework/Platform;ILjava/lang/Throwable;)V
 */
JNIEXPORT void JNICALL Java_cn_sharesdk_ShareSDKUtils_onError
		(JNIEnv * env, jobject thiz, jobject platform, jint action, jobject res);

bool initShareSDK(const char* appKey, bool useAppTrusteeship);

bool stopSDK();

#ifdef __cplusplus
}
#endif
#endif
